### ISSUE TITLE
Problem with free trial license

### ISSUE THREAD

**Issue by khairuzzaman** [clientIO/rappid-tutorial-angular12#2]
Hi,
When I try to install npm with a free trial license, npm install fails. Please see the error screen below. rappid.tgz is in the root directory.
Did I miss anything?

![image](https://user-images.githubusercontent.com/10438018/138126378-db9606de-0b4b-4da7-9796-f938c951226d.png)

**Comment by kumilingus** [comment]
Hi, please try to delete `package-lock.json`, `node_modules` (optionally `npm cache clean --force`) and run `npm install` again.
I think we need to remove `package-lock.json` from this repository (The `rappid.tgz` package checksum differs from the one, which you can download today).
